if (!isServer) exitWith {}; // Tells everyone who is not the server to exit the script here. Everything in a triggers onAct field is done for all clients connected to server so this is important to stop the script running for every client.
//intro
deleteVehicle game_start_npc;
[[0,format["Welcome to Altis Base Defence. Waves will begin shortly, please gear up and take defensive positions!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
_bluhmg1 = "B_MRAP_01_hmg_F" createVehicle getMarkerPos "blu_spawn_hmg1";
_bluhmg1 setDir 308; 
_bluhmg2 = "B_MRAP_01_hmg_F" createVehicle getMarkerPos "blu_spawn_hmg2";
_bluhmg2 setDir 111; 
_bluhmg3 = "B_MRAP_01_hmg_F" createVehicle getMarkerPos "blu_spawn_hmg3";
_bluhmg3 setDir 163; 
_bluhmg4 = "B_MRAP_01_hmg_F" createVehicle getMarkerPos "blu_spawn_hmg4";
_bluhmg4 setDir 352; 
_blumortar1 = "B_Mortar_01_F" createVehicle getMarkerPos "blu_spawn_mortar1";
_blumortar1 setDir 157; 
_blumortar2 = "B_Mortar_01_F" createVehicle getMarkerPos "blu_spawn_mortar2";
_blumortar2 setDir 225; 
_blumortar3 = "B_Mortar_01_F" createVehicle getMarkerPos "blu_spawn_mortar3";
_blumortar3 setDir 290; 
_blumortar4 = "B_Mortar_01_F" createVehicle getMarkerPos "blu_spawn_mortar4";
_blumortar4 setDir 330; 
_blumortar5 = "B_Mortar_01_F" createVehicle getMarkerPos "blu_spawn_mortar5";
_blumortar5 setDir 30; 
_blumortar6 = "B_Mortar_01_F" createVehicle getMarkerPos "blu_spawn_mortar6";
_blumortar6 setDir 72; 
[[0,format["First wave is about to start. Mortars and HMG Hunters have spawned around the base for your use!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
//Round1:
//Infantry Spawns
_opgroup1 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup2 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup19 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup3 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup4 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup1 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup2 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup3 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup4 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup19 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 90;
[[0,format["First Wave has started! Hostile forces incomming contact is imminent!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
//Round2:
sleep 30;
//Infantry Spawns
_opgroup5 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup6 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup7 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup8 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup9 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup10 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup20 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup21 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup5 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup6 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup7 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup8 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup9 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup10 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup20 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup21 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave1",true] spawn BIS_fnc_MP;
[[0,format["Second Wave has started! Hostile reinforcements inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
//Round3:
sleep 20;
//Infantry Spawns
_opgroup11 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup12 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup13 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup14 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup15 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup16 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup17 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup18 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup11 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup12 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup13 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup14 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup15 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup16 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup17 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup18 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave2",true] spawn BIS_fnc_MP;
[[0,format["Third Wave has started! Hostile vehicles have been spotted, prepare yourself!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup1 = creategroup EAST; 
_opoffroad1 = [getMarkerPos "opspawn1", 140, "O_G_Offroad_01_armed_F", _opoffgroup1] call BIS_fnc_spawnVehicle;
_opoffgroup2 = creategroup EAST; 
_opoffroad2 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup2] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup1 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup2 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round4:
sleep 20;
//Infantry Spawns
_opgroup22 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup23 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup24 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup25 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup26 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup27 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup28 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup29 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup22 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup23 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup24 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup25 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup26 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup27 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup28 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup29 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave3",true] spawn BIS_fnc_MP;
[[0,format["Fourth Wave has started! Hostile reinforcements inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup3 = creategroup EAST; 
_opoffroad3 = [getMarkerPos "opspawn3", 140, "O_G_Offroad_01_armed_F", _opoffgroup3] call BIS_fnc_spawnVehicle;
_opoffgroup4 = creategroup EAST; 
_opoffroad4 = [getMarkerPos "opspawn5", 140, "O_G_Offroad_01_armed_F", _opoffgroup4] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup3 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup4 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round5:
sleep 20;
//Infantry Spawns
_opgroup30 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup31 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup32 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup33 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup34 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup35 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup36 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup37 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup30 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup31 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup32 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup33 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup34 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup35 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup36 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup37 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave4",true] spawn BIS_fnc_MP;
[[0,format["Fifth Wave has started! Heavy enemy presence inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup5 = creategroup EAST; 
_opoffroad5 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup5] call BIS_fnc_spawnVehicle;
_opoffgroup6 = creategroup EAST; 
_opoffroad6 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup6] call BIS_fnc_spawnVehicle;
_opoffgroup7 = creategroup EAST; 
_opoffroad7 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup7] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup5 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup6 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup7 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup38 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup39 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup40 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup38 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup39 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup40 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round6:
sleep 20;
//Infantry Spawns
_opgroup41 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup42 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup43 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup44 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup45 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup46 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup47 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup48 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup41 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup42 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup43 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup44 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup45 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup46 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup47 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup48 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave5",true] spawn BIS_fnc_MP;
[[0,format["Sixth Wave has started! Heavy enemy presence inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup8 = creategroup EAST; 
_opoffroad8 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup8] call BIS_fnc_spawnVehicle;
_opoffgroup9 = creategroup EAST; 
_opoffroad9 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup9] call BIS_fnc_spawnVehicle;
_opoffgroup10 = creategroup EAST; 
_opoffroad10 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup10] call BIS_fnc_spawnVehicle;
_opoffgroup11 = creategroup EAST; 
_opoffroad11 = [getMarkerPos "opspawn8", 140, "O_G_Offroad_01_armed_F", _opoffgroup11] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup8 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup9 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup10 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup11 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup49 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup50 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup51 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup52 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup49 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup50 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup51 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup52 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round7:
sleep 20;
//Infantry Spawns
_opgroup53 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup60 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup54 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup55 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup56 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup57 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup58 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup59 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup53 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup54 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup55 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup56 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup57 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup58 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup59 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup60 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave6",true] spawn BIS_fnc_MP;
[[0,format["Seventh Wave has started! Heavy enemy presence inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup12 = creategroup EAST; 
_opoffroad12 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup12] call BIS_fnc_spawnVehicle;
_opoffgroup13 = creategroup EAST; 
_opoffroad13 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup13] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup12 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup13 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup61 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup62 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup63 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup64 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup61 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup62 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup63 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup64 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Ifrit HMG Spawns
_ifrithmggroup1 = creategroup EAST; 
_ifrithmg1 = [getMarkerPos "opspawn6", 140, "O_MRAP_02_hmg_F", _ifrithmggroup1] call BIS_fnc_spawnVehicle;
_ifrithmggroup2 = creategroup EAST; 
_ifrithmg2 = [getMarkerPos "opspawn3", 140, "O_MRAP_02_hmg_F", _ifrithmggroup1] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _ifrithmggroup1 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _ifrithmggroup2 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round8:
sleep 180;
//Infantry Spawns
_opgroup65 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup66 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup67 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup68 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup69 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup70 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup71 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup72 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup65 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup66 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup67 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup68 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup69 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup70 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup71 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup72 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave7",true] spawn BIS_fnc_MP;
[[0,format["Eighth Wave has started! Heavy enemy presence inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup14 = creategroup EAST; 
_opoffroad14 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup14] call BIS_fnc_spawnVehicle;
_opoffgroup15 = creategroup EAST; 
_opoffroad15 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup15] call BIS_fnc_spawnVehicle;
_opoffgroup16 = creategroup EAST; 
_opoffroad16 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup16] call BIS_fnc_spawnVehicle;
_opoffgroup17 = creategroup EAST; 
_opoffroad17 = [getMarkerPos "opspawn8", 140, "O_G_Offroad_01_armed_F", _opoffgroup17] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup14 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup15 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup16 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup17 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup73 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup74 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup75 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup76 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup73 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup74 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup75 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup76 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Ifrit HMG Spawns
_ifrithmggroup3 = creategroup EAST; 
_ifrithmg3 = [getMarkerPos "opspawn1", 140, "O_MRAP_02_hmg_F", _ifrithmggroup3] call BIS_fnc_spawnVehicle;
_ifrithmggroup4 = creategroup EAST; 
_ifrithmg4 = [getMarkerPos "opspawn5", 140, "O_MRAP_02_hmg_F", _ifrithmggroup4] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _ifrithmggroup3 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _ifrithmggroup4 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round9:
sleep 180;
//Infantry Spawns
_opgroup77 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup78 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup79 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup80 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup81 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup82 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup83 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup84 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup77 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup78 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup79 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup80 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup81 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup82 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup83 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup84 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave8",true] spawn BIS_fnc_MP;
[[0,format["Ninth Wave has started! Friendly forces are moving to reinforce your location!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup18 = creategroup EAST; 
_opoffroad18 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup18] call BIS_fnc_spawnVehicle;
_opoffgroup19 = creategroup EAST; 
_opoffroad19 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup19] call BIS_fnc_spawnVehicle;
_opoffgroup20 = creategroup EAST; 
_opoffroad20 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup20] call BIS_fnc_spawnVehicle;
_opoffgroup21 = creategroup EAST; 
_opoffroad21 = [getMarkerPos "opspawn8", 140, "O_G_Offroad_01_armed_F", _opoffgroup21] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup18 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup19 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup20 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup21 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup85 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup86 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup87 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup88 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup85 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup86 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup87 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup88 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Ifrit HMG Spawns
_ifrithmggroup5 = creategroup EAST; 
_ifrithmg5 = [getMarkerPos "opspawn1", 140, "O_MRAP_02_hmg_F", _ifrithmggroup5] call BIS_fnc_spawnVehicle;
_ifrithmggroup4 = creategroup EAST; 
_ifrithmg6 = [getMarkerPos "opspawn5", 140, "O_MRAP_02_hmg_F", _ifrithmggroup6] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _ifrithmggroup5 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _ifrithmggroup6 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round10
sleep 180;
//Infantry Spawns
_opgroup89 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup90 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup91 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup92 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup93 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup94 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup95 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup96 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup89 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup90 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup91 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup92 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup93 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup94 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup95 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup96 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[],"life_fnc_payoutWave9",true] spawn BIS_fnc_MP;
[[0,format["Tenth round started! This is it the final wave. Good Luck - Friendly reinforcements will arrive shortly."]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup22 = creategroup EAST; 
_opoffroad22 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup22] call BIS_fnc_spawnVehicle;
_opoffgroup23 = creategroup EAST; 
_opoffroad23 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup23] call BIS_fnc_spawnVehicle;
_opoffgroup24 = creategroup EAST; 
_opoffroad24 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup24] call BIS_fnc_spawnVehicle;
_opoffgroup25 = creategroup EAST; 
_opoffroad25 = [getMarkerPos "opspawn8", 140, "O_G_Offroad_01_armed_F", _opoffgroup25] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup22 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup23 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup24 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup25 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup97 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup98 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup99 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup100 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup97 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup98 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup99 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup100 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Ifrit HMG Spawns
_ifrithmggroup7 = creategroup EAST; 
_ifrithmg7 = [getMarkerPos "opspawn1", 140, "O_MRAP_02_hmg_F", _ifrithmggroup7] call BIS_fnc_spawnVehicle;
_ifrithmggroup8 = creategroup EAST; 
_ifrithmg8 = [getMarkerPos "opspawn5", 140, "O_MRAP_02_hmg_F", _ifrithmggroup8] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _ifrithmggroup7 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _ifrithmggroup8 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//APC Spawns - RIP
_apcgroup1 = creategroup EAST; 
_apc1 = [getMarkerPos "opspawn3", 140, "O_APC_Tracked_02_cannon_F", _apcgroup1] call BIS_fnc_spawnVehicle;
_apcgroup2 = creategroup EAST; 
_apc2 = [getMarkerPos "opspawn5", 140, "O_APC_Tracked_02_cannon_F", _apcgroup2] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _apcgroup1 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _apcgroup2 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 30;
// Tank Spawns
_tankgroup1 = creategroup EAST; 
_tank1 = [getMarkerPos "opspawn5", 140, "O_MBT_02_cannon_F", _tankgroup1] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _tankgroup1 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
[[0,format["Hold out for 10 more minutes and reinforcements will arrive!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 500;
//blufor aiSpawn - Winning
_bluheligroup1 = creategroup west; 
_bluheli1 = [getMarkerPos "bluaispawn1", 140, "B_Heli_Attack_01_F", _bluheligroup1] call BIS_fnc_spawnVehicle;
_bluheligroup2 = creategroup west; 
_bluheli2 = [getMarkerPos "bluaispawn2", 140, "B_Heli_Attack_01_F", _bluheligroup2] call BIS_fnc_spawnVehicle;
_bluheligroup3 = creategroup west; 
_bluheli3 = [getMarkerPos "bluaispawn3", 140, "B_Heli_Attack_01_F", _bluheligroup3] call BIS_fnc_spawnVehicle;
_bluheligroup4 = creategroup west; 
_bluheli4 = [getMarkerPos "bluaispawn4", 140, "B_Heli_Attack_01_F", _bluheligroup4] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _bluheligroup1 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _bluheligroup2 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _bluheligroup3 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _bluheligroup4 addWaypoint [getmarkerpos "opwp5", 0]; 
_wp1 setWaypointType "DESTROY"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 150;
["Mission Complete",True] call BIS_fnc_endMission;

