if (!isServer) exitWith {}; // Tells everyone who is not the server to exit the script here. Everything in a triggers onAct field is done for all clients connected to server so this is important to stop the script running for every client.
//intro
deleteVehicle game_start_npc;
[[0,format["Welcome to Altis Base Defence. Waves will begin shortly, please gear up and take defensive positions!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
//Round1:
sleep 30;
//Infantry Spawns
_opgroup1 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup2 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup19 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup3 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup4 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup1 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup2 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup3 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup4 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup19 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 100;
[[0,format["First Wave has started! Hostile forces incomming contact is imminent!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
//Round2:
sleep 20;
//Infantry Spawns
_opgroup5 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup6 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup7 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup8 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup9 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup10 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup20 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup21 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup5 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup6 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup7 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup8 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup9 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup10 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup20 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup21 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[0,format["Second Wave has started! Hostile reinforcements inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
//Round3:
sleep 20;
//Infantry Spawns
_opgroup11 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup12 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup13 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup14 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup15 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup16 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup17 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup18 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup11 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup12 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup13 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup14 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup15 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup16 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup17 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup18 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[0,format["Third Wave has started! Hostile vehicles have been spotted, prepare yourself!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup1 = creategroup EAST; 
_opoffroad1 = [getMarkerPos "opspawn1", 140, "O_G_Offroad_01_armed_F", _opoffgroup1] call BIS_fnc_spawnVehicle;
_opoffgroup2 = creategroup EAST; 
_opoffroad2 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup2] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup1 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup2 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round4:
sleep 20;
//Infantry Spawns
_opgroup22 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup23 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup24 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup25 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup26 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup27 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup28 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup29 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup22 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup23 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup24 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup25 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup26 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup27 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup28 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup29 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[0,format["Fourth Wave has started! Hostile reinforcements inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup3 = creategroup EAST; 
_opoffroad3 = [getMarkerPos "opspawn3", 140, "O_G_Offroad_01_armed_F", _opoffgroup3] call BIS_fnc_spawnVehicle;
_opoffgroup4 = creategroup EAST; 
_opoffroad4 = [getMarkerPos "opspawn5", 140, "O_G_Offroad_01_armed_F", _opoffgroup4] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup3 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup4 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round5:
sleep 20;
//Infantry Spawns
_opgroup30 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup31 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup32 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup33 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup34 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup35 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup36 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup37 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup30 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup31 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup32 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup33 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup34 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup35 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup36 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup37 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[0,format["Fifth Wave has started! Heavy enemy presence inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup5 = creategroup EAST; 
_opoffroad5 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup5] call BIS_fnc_spawnVehicle;
_opoffgroup6 = creategroup EAST; 
_opoffroad6 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup6] call BIS_fnc_spawnVehicle;
_opoffgroup7 = creategroup EAST; 
_opoffroad7 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup7] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup5 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup6 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup7 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup38 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup39 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup40 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup38 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup39 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup40 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round6:
sleep 20;
//Infantry Spawns
_opgroup41 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup42 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup43 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup44 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup45 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup46 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup47 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup48 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup41 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup42 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup43 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup44 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup45 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup46 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup47 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup48 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[0,format["Sixth Wave has started! Heavy enemy presence inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup8 = creategroup EAST; 
_opoffroad8 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup8] call BIS_fnc_spawnVehicle;
_opoffgroup9 = creategroup EAST; 
_opoffroad9 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup9] call BIS_fnc_spawnVehicle;
_opoffgroup10 = creategroup EAST; 
_opoffroad10 = [getMarkerPos "opspawn6", 140, "O_G_Offroad_01_armed_F", _opoffgroup10] call BIS_fnc_spawnVehicle;
_opoffgroup11 = creategroup EAST; 
_opoffroad11 = [getMarkerPos "opspawn8", 140, "O_G_Offroad_01_armed_F", _opoffgroup11] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup8 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup9 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup10 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup11 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup49 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup50 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup51 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup52 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup49 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup50 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup51 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup52 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Round7:
sleep 20;
//Infantry Spawns
_opgroup53 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup60 = [getmarkerpos "opspawn5", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup54 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup55 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup56 = [getmarkerpos "opspawn7", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup57 = [getmarkerpos "opspawn2", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup58 = [getmarkerpos "opspawn4", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup59 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_Soldier_GL_F","O_Soldier_AR_F","O_Soldier_LAT_F","O_spotter_F","O_spotter_F","O_recon_M_F","O_sniper_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup53 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup54 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup55 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup56 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup57 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup58 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup59 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup60 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 110;
[[0,format["Seventh Wave has started! Heavy enemy presence inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;
sleep 10;
//Offroad Armed Spawns
_opoffgroup12 = creategroup EAST; 
_opoffroad12 = [getMarkerPos "opspawn2", 140, "O_G_Offroad_01_armed_F", _opoffgroup12] call BIS_fnc_spawnVehicle;
_opoffgroup13 = creategroup EAST; 
_opoffroad13 = [getMarkerPos "opspawn4", 140, "O_G_Offroad_01_armed_F", _opoffgroup13] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _opoffgroup12 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup13 addWaypoint [getmarkerpos "opwp3", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup14 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opoffgroup15 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 10;
//More Infantry spawns
_opgroup61 = [getmarkerpos "opspawn1", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup62 = [getmarkerpos "opspawn3", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup63 = [getmarkerpos "opspawn6", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
_opgroup64 = [getmarkerpos "opspawn8", EAST, ["O_Soldier_SL_F","O_sniper_F","O_spotter_F","O_spotter_F","O_recon_M_F"],[],[],[0.4],[],[],180] call BIS_fnc_spawnGroup;
sleep 2;
_wp1 = _opgroup61 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup62 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup63 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _opgroup64 addWaypoint [getmarkerpos "opwp1", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
//Ifrit HMG Spawns
_ifrithmggroup1 = creategroup EAST; 
_ifrithmg1 = [getMarkerPos "opspawn6", 140, "O_MRAP_02_hmg_F", _ifrithmggroup1] call BIS_fnc_spawnVehicle;
_ifrithmggroup2 = creategroup EAST; 
_ifrithmg2 = [getMarkerPos "opspawn3", 140, "O_MRAP_02_hmg_F", _ifrithmggroup1] call BIS_fnc_spawnVehicle;
sleep 2;
_wp1 = _ifrithmggroup1 addWaypoint [getmarkerpos "opwp4", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
_wp1 = _ifrithmggroup2 addWaypoint [getmarkerpos "opwp2", 0]; 
_wp1 setWaypointType "MOVE"; 
_wp1 setWaypointSpeed "NORMAL"; 
_wp1 setWaypointBehaviour "AWARE"; 
_wp1 setWaypointFormation "STAG COLUMN";
sleep 600;
[[0,format["Seventh Wave has started! Heavy enemy presence inbound!"]],"life_fnc_broadcast",nil,false] spawn life_fnc_MP;